Repository everscale-org/docs, pull requests merged in 2022-07, with the labels that each got.

#241 bridge getting-started upd
  src/develop/integrate/build-cross-chain/getting-started/credit-processor.md
  src/develop/integrate/build-cross-chain/getting-started/eve-everscale-credit-processor.drawio.png
  src/develop/integrate/build-cross-chain/getting-started/everscale-evm.md
  src/develop/integrate/build-cross-chain/getting-started/evm-everscale.md
  src/develop/integrate/build-cross-chain/getting-started/evm-everscale.png
  src/develop/integrate/build-cross-chain/getting-started/tokenomics.md
  src/develop/integrate/build-cross-chain/getting-started/transactions-mechanism.md
Labels: docs for developer

#243 gas managing upd
  src/arch/10-basics.md
  src/arch/20-fee-calculation.md
  src/arch/30-managing-gas.md
  src/develop/smart-contract/learn/20-carefully-working-with-value.md
  src/develop/smart-contract/learn/25-gas-and-messages-limits.md
  src/learn/faq.md
Labels: architecture

#234 Fix types and params in TIP4.4 Storage
  src/standard/TIP-4/4.md
Labels: TIP, NFT
