Repository everscale-org/docs, pull requests merged in 2023-05, with the labels that each got.

#327 chore: update urls
  .build/website/link/footer.js
  .build/website/link/navbar.js
  .build/website/package.json
  .build/website/script/build-pdf.sh
  .build/website/yarn.lock
Labels: enhancement

#331 Add GraphQL code generation guide
  src/develop/payment.md
Labels: for Developer, enhancement, for Project

#337 chore: fix 404 on page standard/TIP-1
  src/standard/TIP-1/_category_.json
Labels: bug
